import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { MSWComponent } from '@/app/_component/MSWCoponent';
import './globals.css';

if (
  process.env.NEXT_RUNTIME === 'nodejs' &&
  process.env.NODE_ENV !== 'production'
) {
  const { server } = require('@/mocks/msw/http');
  server.listen();
}

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'SNS App',
  description: 'Generated by create next app',
};

type Props = {
  children: React.ReactNode;
  modal: React.ReactNode;
};

export default function RootLayout({ children, modal }: Props) {
  return (
    <html lang='en'>
      <body className={inter.className}>
        <MSWComponent />
        {children}
        {modal}
      </body>
    </html>
  );
}
